services:
  backend:
    build: ./typing_trainer_rest 
    # command: python /app/manage.py runserver 0.0.0.0:8000
    command: gunicorn ./typing_trainer_rest/typing_trainer.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev

  frontend:
    build: ./frontend_vue
    ports:
      - "5173:5173"