services:
  backend:
    build: ./typing_trainer_rest 
    # command: python /app/manage.py runserver 0.0.0.0:8000
    command: gunicorn typing_trainer.wsgi:application --bind 0.0.0.0:8000
    # command: gunicorn myapp.wsgi:application --bind unix:/tmp/gunicorn.sock
    # ports:
    #   - "8000:8000"
    volumes:
      - static_volume:/app/static
    expose:
      - 8000
    env_file:
      - ./.env.dev

  fronted:
    build: ./frontend_vue
    volumes:
      - vue_dist:/app/dist

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/app/static
      - vue_dist:/app/vue/dist
    depends_on:
      - backend

volumes:
  static_volume:
  vue_dist: